version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  precise:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  ai_file:
    class: logging.FileHandler
    level: DEBUG
    formatter: precise
    filename: ai.log
    encoding: utf8
    mode: w
  board_file:
    class: logging.FileHandler
    level: DEBUG
    formatter: precise
    filename: board.log
    encoding: utf8
    mode: w
loggers:
  ai:
    level: DEBUG
    handlers: [console, ai_file]
    propagate: no
root:
  level: DEBUG
  handlers: [console, board_file]
