version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  precise:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  board_file:
    class: logging.FileHandler
    level: DEBUG
    formatter: precise
    filename: board.log
    encoding: utf8
    mode: w
  game_file:
    class: logging.FileHandler
    level: DEBUG
    formatter: precise
    filename: game.log
    encoding: utf8
    mode: w
  ai_file:
    class: logging.FileHandler
    level: DEBUG
    formatter: precise
    filename: ai.log
    encoding: utf8
    mode: w
loggers:
  board:
    level: DEBUG
    handlers: [board_file]
    propagate: no
  game:
    level: DEBUG
    handlers: [game_file]
    propagate: no
  ai:
    level: DEBUG
    handlers: [ai_file]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
